### ISSUE TITLE
Setting config.LogLevel does nothing

### ISSUE THREAD

**Issue by ncw** [qingstor/qingstor-sdk-go#122]
I'm trying to disable the logging from this package, but I don't seem to be able to.

I expected setting `config.LogLevel = "fatal"` would work but it doesn't do anything, eg

```go
	cf, err := qsConfig.NewDefault()
	if err != nil {
		return nil, err
	}
	cf.AccessKeyID = accessKeyID
	cf.SecretAccessKey = secretAccessKey
	cf.Protocol = protocol
	cf.Host = host
	cf.Port = port
	cf.Connection = fshttp.NewClient(ctx)
	cf.LogLevel = "fatal" // Valid log levels are "debug", "info", "warn", "error", and "fatal".
```

This is perhaps not suprising since `LogLevel` is never used!

```
~/go/src/github.com/qingstor/qingstor-sdk-go$ git grep LogLevel
config/config.go:       LogLevel string `yaml:"log_level"`
config/config_test.go:          LogLevel:        "warn",
config/config_test.go:  assert.Equal(t, "warn", c.LogLevel)
```

How can I disable the logging?

**Comment by Xuanwo** [comment]
ping @Prnyself to take a look.

**Comment by Prnyself** [comment]
From `qingstor-sdk-go` `v4.1.0`, we do not set logger in sdk any more. Instead, we use [qingstor/log](https://github.com/qingstor/log), which is higher performance and more reliable. If you want to disable logging, just conduct your own logger with `MatchHigherLevel`, and pass it by context, for instance:
```go
import "github.com/qingstor/log"

// example func
func ExampleLog() {
	tf, err := NewText(&TextConfig{
		// Use unix timestamp nano for time
		TimeFormat: TimeFormatUnixNano,
		// Use upper case level
		LevelFormat: level.UpperCase,
		EntryFormat: "[{level}] - {time} {value}",
	})
	if err != nil {
		println("text config created failed for: ", err)
		os.Exit(1)
	}

	e := ExecuteMatchWrite(
		// Only print log that level is higher than Debug.
		MatchHigherLevel(level.Debug),
		// Write into stderr.
		os.Stderr,
	)

	logger := New().WithExecutor(e).WithTransformer(tf)
	ctx := log.ContextWithLogger(context.Background(), logger)
	qsService.ListBucketsWithContext(ctx, listBucketInput)
}
```

Sorry for the disturbance. We will disable the `LogLevel` (and other not-used fields, if there are any) in config with next release.

**Comment by ncw** [comment]
Thank you for the example.

That seems a lot of work just to turn off the debug logs!

I think I can plumb in my own logging system with that though.

Thank you

**Comment by Prnyself** [comment]
OK. 
Again, sorry for the inconvenience, and I'll close this issue. Plz feel free to reopen it if needed.
