### ISSUE TITLE
can i cancel a request of bucket.PutObject

### ISSUE THREAD

**Issue by idy** [qingstor/qingstor-sdk-go#15]
I'm implementing a qingstor driver for [docker registry](https://github.com/docker/distribution/blob/master/registry/storage/driver). 

I found there is no where to pass a context object to the function and neither the returned object `PutObjectOutput` has a `Cancel`method.

**Comment by pengsrc** [comment]
You can create a `Request` struct which contains then the `HTTPRequest` and `HTTPResponse` by calling `PutObjectRequest`.

``` go
request, output, err := bucket.PutObjectRequest("object", &qs.PutObjectInput{Body: file})
```

https://github.com/yunify/qingstor-sdk-go/blob/master/request/request.go#L34-L42

**Comment by yangjunsss** [comment]
@idy  Hi, we have implemented the QingStor driver already, we will make PR ASAP. But BTW I can't see there is  something need to pass context object and call ``Cancel`` method. Can you give any comments?

**Comment by idy** [comment]
To implement the methods defined in `StorageDirver` interface, such as `PutContent(ctx context.Context, path string, content []byte) error`, we need handle the case that the data transferring is not finished while context's deadline is reached.

**Comment by idy** [comment]
Could you give me the source code of `driver` and the `cmd/main.go`?  I want to build a binary to run test the docker registry.
Thanks a lot ~

**Comment by idy** [comment]
@prettyxw Do you mean that I create a `PutObjectRequest` first, and then replace the `req.HTTPRequest` with `req.HTTPRequest.WithContext` and send the request ?

**Comment by pengsrc** [comment]
@idy I'm not familiar with docker registry driver. I mean you can access to the actually `http.Request ` struct, and do anything you want.

**Comment by yangjunsss** [comment]
@idy  I will fork the ``distribution`` project and public our commits this week.  ```PutContent``` return Error directly when is not finished. I paste some code here 

```go
// PutContent stores the []byte content at a location designated by "path".
func (d *driver) PutContent(ctx context.Context, path string, content []byte) error {
	hashInBytes := md5.Sum(content)
	md5String := hex.EncodeToString(hashInBytes[:16])
	// Perform Put Object

	output, err := d.qsBucket.PutObject(d.qsPath(path), &service.PutObjectInput{
		ContentType: service.String(d.getContentType()),
		ContentMD5:  service.String(md5String),
		Body:        bytes.NewReader(content),
	})
	logger.Infof("Put content to path[%v] with md5[%v] size[%d] and err[%v] output[%+v] ", path, md5String, len(content), err, output)
	return parseError(path, err)
}
```

**Comment by idy** [comment]
The first arg `ctx` has a cancel channel, which can give caller the ability to cancel a long time request. In this case, `d.qsBucket.PutObject` may take a long time, and the caller might cancel the request with `ctx`.

**Comment by idy** [comment]
@prettyxw 
I cannot get HTTPRequest from req, it's a nil pointer.
```go
func (d *Driver) GetContent(ctx context.Context, path string) ([]byte, error) {
	req, o, err := d.bucket.GetObjectRequest(path, &service.GetObjectInput{})
	wb := &bytes.Buffer{}
	if err != nil {
		return wb.Bytes(), err
	}
	req.HTTPRequest = req.HTTPRequest.WithContext(ctx)
	if err := req.Send(); err != nil {
		return wb.Bytes(), err
	}
	defer o.Body.Close()

	_, err = io.Copy(wb, o.Body)
	return wb.Bytes(), err
}
```

**Comment by yangjunsss** [comment]
What's the err? 
BTW, the path should be formatted to ```RootDirectory/path/```

**Comment by pengsrc** [comment]
Hi, I will close this issue if there's no further questions.
