### ISSUE TITLE
Please add dependency into vendor directory. 

### ISSUE THREAD

**Issue by MartinForReal** [qingstor/qingstor-sdk-go#56]
Is it possible to add dependencies into vendor dir? Thanks!

**Comment by yangjunsss** [comment]
It seems there is a indirect dependence when other project use `qingstor-sdk`? Our concern is from 
https://github.com/docker/distribution/pull/2196. Please confirm,tks.

**Comment by pengsrc** [comment]
Yeah, we use [glide](http://glide.sh) to manage project dependencies.

**Comment by MartinForReal** [comment]
As an end user I don't care what library the sdk depends on. Could you please add library into vendor dir so that I don't need to manage the version of sdk dependencies? Some projects such as docker/distribution use gonvendor as dependency management tool and one should check the source code of sdk to deduce which version of dependencies to use before he can write their own business logic. I don't think this is a user-friendly experience.

**Comment by pengsrc** [comment]
Reasonable, I'll add it.

**Comment by pengsrc** [comment]
https://github.com/yunify/qingstor-sdk-go/pull/59
