### ISSUE TITLE
bucket.PutObject don't support  Meta ?

### ISSUE THREAD

**Issue by haozibi** [qingstor/qingstor-sdk-go#66]
https://github.com/yunify/qingstor-sdk-go/blob/d82d0bc870ee54bf0bb23f015713ee4180418ddf/service/object.go#L964-L1009

![image](https://user-images.githubusercontent.com/13708418/56546705-b2802180-65ad-11e9-9c3a-5fee31b3d663.png)

bucket.PutObject 不支持上传 Object 时候的自定义 Metadata ？

**Comment by Xuanwo** [comment]
目前 SDK 还不支持在 PutObject 的时候指定 Metadata，我们会尽快提供这个功能。

此外，如果是通过 AWS S3 兼容接口来调用 QingStor 对象存储服务的话，可以直接使用 S3 Go SDK 提供的 Metadata 功能。

**Comment by Xuanwo** [comment]
Supported in https://github.com/yunify/qingstor-sdk-go/pull/70
