### ISSUE TITLE
API and SDK not uniform

### ISSUE THREAD

**Issue by haozibi** [qingstor/qingstor-sdk-go#67]
[GET Bucket (List Objects)](https://docs.qingcloud.com/qingstor/api/bucket/get.html)

![image](https://user-images.githubusercontent.com/13708418/56653204-c3b95300-66bf-11e9-814b-f4ef283a1a27.png)

https://github.com/yunify/qingstor-sdk-go/blob/d82d0bc870ee54bf0bb23f015713ee4180418ddf/service/bucket.go#L1072-L1098

I don't find `has_more` response

Maybe I can pull requests

**Comment by Xuanwo** [comment]
Yes.

You can make a PR to https://github.com/yunify/qingstor-api-specs so that we can generate the SDK against the latest API Specs.

**Comment by haozibi** [comment]
> Yes.
> 
> You can make a PR to https://github.com/yunify/qingstor-api-specs so that we can generate the SDK against the latest API Specs.

你的意思是这个 SDK 是通过  https://github.com/yunify/qingstor-api-specs 自动生成的？

**Comment by Xuanwo** [comment]
是的

**Comment by haozibi** [comment]
> 是的

I noticed that someone submitted the `has_more` field before, why is the SDK not? Is the SDK not updated in time?

https://github.com/yunify/qingstor-api-specs/pull/27

**Comment by Xuanwo** [comment]
Thanks for you PR, SDK has been regenerated in https://github.com/yunify/qingstor-sdk-go/commit/d60a6b3ce2427d128d44b466a13428f4a40dc89f.
